#!/usr/bin/env ruby


require 'rack'
require 'launchy'

port = 4321
print "Your shell command:\n> "
shell_command_output = `#{gets.chomp}`
web_app = lambda do |env|
  [200, {'Content-Type' => 'text/html'},
   ["<pre>#{shell_command_output}</pre>"]]
end

Launchy.open("http://localhost:#{port}")
Rack::Handler::WEBrick.run web_app, :Port => port
